apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
spec:
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
      - name: axion-ui
        image: acrdevtodoacr.azurecr.io/axionuidev:12a76671810788b940829c0052f846d3697c8421
        ports:
        - containerPort: 80
