apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
spec:
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
      - name: axion-ui
        image: acrdevtodoacr.azurecr.io/axionuidev:1fe96d36eab67b6da5075a2bd06aa7e104d4d82f
        ports:
        - containerPort: 80
