apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
spec:
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
      - name: axion-ui
        image: acrdevtodoacr.azurecr.io/axionuidev:f601eb4ed981c5fd8d9f929c47e33b4dc9e7ae20
        ports:
        - containerPort: 80
