apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-ui.yaml


images:
  - name: acrdevtodoacr.azurecr.io/axion-ui
    newTag: v3        # CI isko har build par replace karega