name: Trigger auto deployment for axion-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/axion-ui-AutoDeployTrigger-016ea381-aca6-41d3-9b32-5be23de45970.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AXIONUI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AXIONUI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AXIONUI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.AXIONUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AXIONUI_REGISTRY_PASSWORD }}
          containerAppName: axion-ui
          resourceGroup: axion-ui-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


