name: Trigger auto deployment for axion-ui-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/axion-ui-test-AutoDeployTrigger-e4ed0bdf-756c-41a7-9ffa-b3b3aad01a85.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AXIONUITEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AXIONUITEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AXIONUITEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: <ACR_NAME>.azurecr.io
          registryUsername: ${{ secrets.AXIONUITEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AXIONUITEST_REGISTRY_PASSWORD }}
          containerAppName: axion-ui-test
          resourceGroup: rg-test
          imageToBuild: <ACR_NAME>.azurecr.io/axion-ui:${{ github.sha }}
          targetPort: 80
          ingress: external
